-- Criação de Sequences

CREATE SEQUENCE TICKET_SEQ;
CREATE SEQUENCE ORIGEM_CHAMADO_SEQ;
CREATE SEQUENCE PRIORIDADE_SEQ;
CREATE SEQUENCE SETOR_SEQ;
CREATE SEQUENCE SISTEMA_SEQ;
CREATE SEQUENCE STATUS_COPERGAS_SEQ;
CREATE SEQUENCE STATUS_FORNECEDOR_SEQ;
CREATE SEQUENCE STATUS_SEQ;
CREATE SEQUENCE TICKET_CATEGORIA_SEQ;
CREATE SEQUENCE TICKET_SUB_CATEGORIA_SEQ;
CREATE SEQUENCE TIPO_ATENDIMENTO_SEQ;
CREATE SEQUENCE TIPO_CHAMADO_SEQ;
CREATE SEQUENCE PRODUTO_CATEGORIA_SEQ;
CREATE SEQUENCE PRODUTO_SEQ;
CREATE SEQUENCE REGISTRO_IMPORTACAO_SEQ;
CREATE SEQUENCE USUARIO_SEQ;


-- Criação de Tabelas

CREATE TABLE TICKET_CATEGORIA (
   ID INTEGER NOT NULL ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE TICKET_SUB_CATEGORIA (
   ID INTEGER NOT NULL ,
   TICKET_CATEGORIA_ID INTEGER ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) ,
   CONSTRAINT TICA_TISC_FK FOREIGN KEY (TICKET_CATEGORIA_ID) REFERENCES TICKET_CATEGORIA
);

CREATE TABLE SETOR (
   ID INTEGER NOT NULL ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE TIPO_CHAMADO (
   ID INTEGER NOT NULL ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE ORIGEM_CHAMADO (
   ID INTEGER NOT NULL ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE SISTEMA (
   ID INTEGER NOT NULL ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE STATUS_COPERGAS (
   ID INTEGER NOT NULL ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE STATUS_FORNECEDOR (
   ID INTEGER NOT NULL ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE STATUS (
   ID INTEGER NOT NULL ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE PRIORIDADE (
   ID INTEGER NOT NULL ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE TIPO_ATENDIMENTO (
   ID INTEGER NOT NULL ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE PRODUTO_CATEGORIA (
   ID INTEGER NOT NULL ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE PRODUTO (
   ID INTEGER NOT NULL ,
   PRODUTO_CATEGORIA_ID INTEGER NOT NULL ,
   CODIGO VARCHAR(5) NOT NULL ,
   DESCRICAO VARCHAR(100) NOT NULL ,
   DATA TIMESTAMP ,
   VALOR NUMERIC ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) ,
   CONSTRAINT PRCA_PROD_FK FOREIGN KEY (PRODUTO_CATEGORIA_ID) REFERENCES PRODUTO_CATEGORIA
);

CREATE TABLE REGISTRO_IMPORTACAO (
   ID INTEGER NOT NULL ,
   QTD_TICKET_INSERIDOS INTEGER ,
   QTD_TICKET_ALTERADOS INTEGER ,
   QTD_TICKET_PROCESSADOS INTEGER ,
   DT_ULTIMA_IMPORTACAO TIMESTAMP ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE USUARIO (
   ID INTEGER NOT NULL ,
   NOME VARCHAR(100) NOT NULL ,   
   DT_ULTIMA_IMPORTACAO DATE ,
   NR_VERSAO INTEGER NOT NULL ,
   DT_ULTMA_ALTERACAO DATE NOT NULL ,
   IN_USO BOOLEAN NOT NULL ,
   PRIMARY KEY (ID) 
);

CREATE TABLE TICKET (
	ID INTEGER NOT NULL ,
   	NUMERO VARCHAR(30) NOT NULL ,
   	MAQUINA_ORIGEM VARCHAR(100) ,
   	USUARIO_ID INTEGER ,
   	CATEGORIA_ID INTEGER ,
	SUB_CATEGORIA_ID INTEGER ,
    DT_CRIACAO TIMESTAMP ,
    DT_VENCIMENTO TIMESTAMP ,
    DT_FECHAMENTO TIMESTAMP ,
    TITULO VARCHAR(150) ,
    DESCRICAO VARCHAR(100000) ,
    FECHAMENTO_ENCAMINHADO BOOLEAN ,
    SETOR_ID INTEGER ,
    SOLICITANTE VARCHAR(150) ,
    TIPO_CHAMADO_ID INTEGER ,
    ORIGEM_CHAMADO_ID INTEGER ,
    SISTEMA_ID INTEGER ,
    STATUS_COPERGAS_ID INTEGER ,
    STATUS_FORNECEDOR_ID INTEGER ,
    STATUS_ID INTEGER ,
    PRIORIDADE_ID INTEGER ,
    FOI_REABERTO BOOLEAN ,
    TIPO_ATENDIMENTO_ID INTEGER ,
   	NR_VERSAO INTEGER NOT NULL ,
   	DT_ULTMA_ALTERACAO DATE NOT NULL ,
   	IN_USO BOOLEAN NOT NULL ,
   	PRIMARY KEY (ID) ,
   	CONSTRAINT USUA_TICK_FK FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO ,
   	CONSTRAINT TICA_TICK_FK FOREIGN KEY (CATEGORIA_ID) REFERENCES TICKET_CATEGORIA ,
   	CONSTRAINT TISC_TICK_FK FOREIGN KEY (SUB_CATEGORIA_ID) REFERENCES TICKET_SUB_CATEGORIA ,
   	CONSTRAINT SETO_TICK_FK FOREIGN KEY (SETOR_ID) REFERENCES SETOR ,
   	CONSTRAINT TICH_TICK_FK FOREIGN KEY (TIPO_CHAMADO_ID) REFERENCES TIPO_CHAMADO ,
   	CONSTRAINT ORCH_TICK_FK FOREIGN KEY (ORIGEM_CHAMADO_ID) REFERENCES ORIGEM_CHAMADO ,
   	CONSTRAINT SIST_TICK_FK FOREIGN KEY (SISTEMA_ID) REFERENCES SISTEMA ,
   	CONSTRAINT STCO_TICK_FK FOREIGN KEY (STATUS_COPERGAS_ID) REFERENCES STATUS_COPERGAS ,
   	CONSTRAINT STFO_TICK_FK FOREIGN KEY (STATUS_FORNECEDOR_ID) REFERENCES STATUS_FORNECEDOR ,
   	CONSTRAINT STAT_TICK_FK FOREIGN KEY (STATUS_ID) REFERENCES STATUS ,
   	CONSTRAINT PRIO_TICK_FK FOREIGN KEY (PRIORIDADE_ID) REFERENCES PRIORIDADE ,
   	CONSTRAINT TIAT_TICK_FK FOREIGN KEY (TIPO_ATENDIMENTO_ID) REFERENCES TIPO_ATENDIMENTO
);


-- Carga Inicial

INSERT INTO STATUS (ID, DESCRICAO, NR_VERSAO, DT_ULTMA_ALTERACAO, IN_USO) VALUES ((SELECT NEXTVAL('STATUS_SEQ')), 'open', 0, CURRENT_TIMESTAMP, TRUE);
INSERT INTO STATUS (ID, DESCRICAO, NR_VERSAO, DT_ULTMA_ALTERACAO, IN_USO) VALUES ((SELECT NEXTVAL('STATUS_SEQ')), 'closed', 0, CURRENT_TIMESTAMP, TRUE);

INSERT INTO USUARIO (ID, NOME, NR_VERSAO, DT_ULTMA_ALTERACAO, IN_USO) VALUES ((SELECT NEXTVAL('USUARIO_SEQ')), 'unassigned', 0, CURRENT_TIMESTAMP, TRUE);

INSERT INTO REGISTRO_IMPORTACAO (ID, NR_VERSAO, DT_ULTMA_ALTERACAO, IN_USO) VALUES ((SELECT NEXTVAL('REGISTRO_IMPORTACAO_SEQ')), 0, CURRENT_TIMESTAMP, TRUE);
